### ISSUE TITLE
Leaderboard/Database/Backend

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#1266]
# Todo List

- [ ] fix embed not updating with git repo rsync
- [ ] discord user login (to track submissions)
- [ ] rudimentary submission interface
- [ ] submission api end point
- [ ] submission pre-compute store
- [ ] compute work queue; get work and submit work end point
- [ ] compute client
- [ ] discord bot for role verification

# System Design and Implementation Notes

![Image](https://user-images.githubusercontent.com/906239/215653457-f0818336-d928-4d7d-98f6-ea68dfebdd83.png)

## Submission Process

Submissions is for any pending requests. There will be sims that exist on submissions that don't exist on the db.

1. user submits a sim
2. sim gets added to submission collection (assuming compute has to rerun sim before it gets here)
3. submission entry gets tagged with all active tags (1 column per tag vs array?). If submission has tag, means that tag has not yet reviewed that submission
4. management interface notifies all tms about new submission
5. a tm accepts the submission. New db entry is created from this submission entry. Note: the db entry _id should be the same as the submission entry _id (so manually set it in db, let mongo gen in submission)
6. submission entry has tag removed (step 5 is skipped if reject, so just removes tag without creating new entry)
7. another tm accepts the submission. Because a db entry already exists with this same submission _id, db entry just gets updated with the new tag added
8. submission entry has tag removed (step 7 skipped if reject)
9. After all tags have reviewed the submission, safe to delete submission entry

On the management side (assuming bot), you have the following commands:
* !list: lists all pending submissions that still have your tag on them
* !accept: accepts a pending submission
* !reject: rejects a pending submission
* !tag: tag a sim in db manually
* !untag: untag a sim in db manually (if a db entry no longer has any tags, delete)

## Submission Interface

**Submission:**
* add login functionality to simpact.app
* once logged in, user can see submit page which is just 2 text boxes for description + config (maybe a button to import from viewer link)
* future: should also show status of existing submissions somewhere on user page

**Management:**
* add basic mgmt functionality to simpact.app
* on user login, if user has the specified tag's mgmt role in discord (will need a bot in discord to check this), then the mgmt page will be available. gets rid of the need to write something to manage users and let us just use discord roles
* management should have a drop down for one page for each tag that the person has roles for
* manage page should be just a very basic list of sims + 2 buttons (approve/deny) 

## Discord Role Bot

Purpose of this bot is to keep track of discord user roles (for premium accounts and tag management purposes). Implementation notes:

* the api service should define an interface representing a `RoleChecker` that, when given a user id, will return a list (or map) of roles that the user has. 
* the api service should provide a list of acceptable roles
* the discord bot should implement this `RoleChecker` interface
* the discord bot needs to reconcile between the appropriate discord roles and the api service role consts

**Comment by srliao** [comment]
Currently WIP in https://github.com/genshinsim/gcsim/tree/feature-stats-rework

**Comment by srliao** [comment]
some items on here still missing but closing; will open new issues for stuff not done yet
