### ISSUE TITLE
check implementation of buffs that depend on deployables

### ISSUE THREAD

**Issue by k0l11** [genshinsim/gcsim#654]
These buffs should be checked:
- [x] Albedo C4, C6 (fixed by #739)
- [x] Traveler (Geo) C1 (fixed by #734) 
- [x] Shenhe Q res shred, A1, C2 (fixed by #689)
- [x] Jean C4 (fixed by #741)
- [x] Kazuha C2 (fixed by #738)

These buffs should apply on ticks like Bennett Q / Ganyu A4 / Gorou E / ... and be affected by hitlag (don't forget this part).

**Comment by k0l11** [comment]
fixes for all the listed abilities have been merged.
