### ISSUE TITLE
Rewrite checklist - before going live on prod

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#699]
Following is a list of things that needs to be done before we can push live into production

## General checklist

- [x] Add old energy interval syntax back in
- [x] Discord bot to handle database submissions
- [x] containerize embed generator

## Character hitlag checklist

- [x] itto
- [x] heizou
- [x] hutao
- [x] kuki
- [x] noelle
- [x] shenhe (depends on #654)
- [x] tartaglia 
- [x] traveleranemo
- [x] travelerelectro
- [x] travelergeo
- [x] yoimiya

## Weapon/artifact hitlag checklist

- [x] amenoma kageuchi 30s seed duration timer

## Not doing for now

These are todos that are pushed back and will not be part of rewrite 
- [ ] 4 tom shield bonus mod (core change)
- [ ] UI for sharing and managing permanent links (registered users only)
- [ ] new DB UI
- [ ] raiden E eye (#657)
- [ ] wine and song stam percent mod (core change)
- [ ] bloodstained stam percent mod (core change)

**Comment by srliao** [comment]
`new DB UI` is sort of... working

**Comment by srliao** [comment]
See https://github.com/genshinsim/gcsim/issues/657#issuecomment-1216766959 re Raiden E

**Comment by k0l11** [comment]
leaving it here so it's not forgotten: 4 bloodstained stam percent mod should also go on the list

**Comment by k0l11** [comment]
also Not doing for now:
- hurt syntax
- attack_delay, charge_delay, ... (AfterAction hook)
- apl
